name: untitled
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  qrscan: ^0.3.2
  permission_handler: ^8.1.3
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  flutter_launcher_icons: ^0.9.0
  sp_util: ^2.0.3
  splash_screen_view: ^3.0.0
  fluttertoast: ^8.0.7
  connectivity: ^3.0.6
  cool_alert: ^1.1.0
  internet_connection_checker: ^0.0.1+2
  http: ^0.13.3
  dio: ^4.0.0
  getwidget: ^2.0.3
  visibility_detector: ^0.2.0
  flutter_slidable: ^0.6.0





flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpeg"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
     - assets/
  fonts:
    - family: amiri-italic
      fonts:
        - asset: fonts/Amiri-Italic.ttf

    - family: amiri-regular
      fonts:
        - asset: fonts/Amiri-Regular.ttf

    - family: amiri-bolditalic
      fonts:
        - asset: fonts/Amiri-BoldItalic.ttf

    - family: amiri-bold
      fonts:
        - asset: fonts/Amiri-Bold.ttf

